/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BokaRumRouteImport } from './routes/boka-rum'
import { Route as BokaKonferensRouteImport } from './routes/boka-konferens'
import { Route as IndexRouteImport } from './routes/index'

const BokaRumRoute = BokaRumRouteImport.update({
  id: '/boka-rum',
  path: '/boka-rum',
  getParentRoute: () => rootRouteImport,
} as any)
const BokaKonferensRoute = BokaKonferensRouteImport.update({
  id: '/boka-konferens',
  path: '/boka-konferens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boka-konferens': typeof BokaKonferensRoute
  '/boka-rum': typeof BokaRumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boka-konferens': typeof BokaKonferensRoute
  '/boka-rum': typeof BokaRumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boka-konferens': typeof BokaKonferensRoute
  '/boka-rum': typeof BokaRumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boka-konferens' | '/boka-rum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boka-konferens' | '/boka-rum'
  id: '__root__' | '/' | '/boka-konferens' | '/boka-rum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BokaKonferensRoute: typeof BokaKonferensRoute
  BokaRumRoute: typeof BokaRumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boka-rum': {
      id: '/boka-rum'
      path: '/boka-rum'
      fullPath: '/boka-rum'
      preLoaderRoute: typeof BokaRumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boka-konferens': {
      id: '/boka-konferens'
      path: '/boka-konferens'
      fullPath: '/boka-konferens'
      preLoaderRoute: typeof BokaKonferensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BokaKonferensRoute: BokaKonferensRoute,
  BokaRumRoute: BokaRumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
