/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NyheterRouteImport } from './routes/nyheter'
import { Route as LangtidsboendeRouteImport } from './routes/langtidsboende'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GalleriRouteImport } from './routes/galleri'
import { Route as BokaRumRouteImport } from './routes/boka-rum'
import { Route as BokaKonferensRouteImport } from './routes/boka-konferens'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RumGrandLitRouteImport } from './routes/rum.grand-lit'
import { Route as RumEnkelrumRouteImport } from './routes/rum.enkelrum'
import { Route as RumDubbelrumRouteImport } from './routes/rum.dubbelrum'

const NyheterRoute = NyheterRouteImport.update({
  id: '/nyheter',
  path: '/nyheter',
  getParentRoute: () => rootRouteImport,
} as any)
const LangtidsboendeRoute = LangtidsboendeRouteImport.update({
  id: '/langtidsboende',
  path: '/langtidsboende',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriRoute = GalleriRouteImport.update({
  id: '/galleri',
  path: '/galleri',
  getParentRoute: () => rootRouteImport,
} as any)
const BokaRumRoute = BokaRumRouteImport.update({
  id: '/boka-rum',
  path: '/boka-rum',
  getParentRoute: () => rootRouteImport,
} as any)
const BokaKonferensRoute = BokaKonferensRouteImport.update({
  id: '/boka-konferens',
  path: '/boka-konferens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RumGrandLitRoute = RumGrandLitRouteImport.update({
  id: '/rum/grand-lit',
  path: '/rum/grand-lit',
  getParentRoute: () => rootRouteImport,
} as any)
const RumEnkelrumRoute = RumEnkelrumRouteImport.update({
  id: '/rum/enkelrum',
  path: '/rum/enkelrum',
  getParentRoute: () => rootRouteImport,
} as any)
const RumDubbelrumRoute = RumDubbelrumRouteImport.update({
  id: '/rum/dubbelrum',
  path: '/rum/dubbelrum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boka-konferens': typeof BokaKonferensRoute
  '/boka-rum': typeof BokaRumRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/langtidsboende': typeof LangtidsboendeRoute
  '/nyheter': typeof NyheterRoute
  '/rum/dubbelrum': typeof RumDubbelrumRoute
  '/rum/enkelrum': typeof RumEnkelrumRoute
  '/rum/grand-lit': typeof RumGrandLitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boka-konferens': typeof BokaKonferensRoute
  '/boka-rum': typeof BokaRumRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/langtidsboende': typeof LangtidsboendeRoute
  '/nyheter': typeof NyheterRoute
  '/rum/dubbelrum': typeof RumDubbelrumRoute
  '/rum/enkelrum': typeof RumEnkelrumRoute
  '/rum/grand-lit': typeof RumGrandLitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boka-konferens': typeof BokaKonferensRoute
  '/boka-rum': typeof BokaRumRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/langtidsboende': typeof LangtidsboendeRoute
  '/nyheter': typeof NyheterRoute
  '/rum/dubbelrum': typeof RumDubbelrumRoute
  '/rum/enkelrum': typeof RumEnkelrumRoute
  '/rum/grand-lit': typeof RumGrandLitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boka-konferens'
    | '/boka-rum'
    | '/galleri'
    | '/kontakt'
    | '/langtidsboende'
    | '/nyheter'
    | '/rum/dubbelrum'
    | '/rum/enkelrum'
    | '/rum/grand-lit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boka-konferens'
    | '/boka-rum'
    | '/galleri'
    | '/kontakt'
    | '/langtidsboende'
    | '/nyheter'
    | '/rum/dubbelrum'
    | '/rum/enkelrum'
    | '/rum/grand-lit'
  id:
    | '__root__'
    | '/'
    | '/boka-konferens'
    | '/boka-rum'
    | '/galleri'
    | '/kontakt'
    | '/langtidsboende'
    | '/nyheter'
    | '/rum/dubbelrum'
    | '/rum/enkelrum'
    | '/rum/grand-lit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BokaKonferensRoute: typeof BokaKonferensRoute
  BokaRumRoute: typeof BokaRumRoute
  GalleriRoute: typeof GalleriRoute
  KontaktRoute: typeof KontaktRoute
  LangtidsboendeRoute: typeof LangtidsboendeRoute
  NyheterRoute: typeof NyheterRoute
  RumDubbelrumRoute: typeof RumDubbelrumRoute
  RumEnkelrumRoute: typeof RumEnkelrumRoute
  RumGrandLitRoute: typeof RumGrandLitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nyheter': {
      id: '/nyheter'
      path: '/nyheter'
      fullPath: '/nyheter'
      preLoaderRoute: typeof NyheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/langtidsboende': {
      id: '/langtidsboende'
      path: '/langtidsboende'
      fullPath: '/langtidsboende'
      preLoaderRoute: typeof LangtidsboendeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleri': {
      id: '/galleri'
      path: '/galleri'
      fullPath: '/galleri'
      preLoaderRoute: typeof GalleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boka-rum': {
      id: '/boka-rum'
      path: '/boka-rum'
      fullPath: '/boka-rum'
      preLoaderRoute: typeof BokaRumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boka-konferens': {
      id: '/boka-konferens'
      path: '/boka-konferens'
      fullPath: '/boka-konferens'
      preLoaderRoute: typeof BokaKonferensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rum/grand-lit': {
      id: '/rum/grand-lit'
      path: '/rum/grand-lit'
      fullPath: '/rum/grand-lit'
      preLoaderRoute: typeof RumGrandLitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rum/enkelrum': {
      id: '/rum/enkelrum'
      path: '/rum/enkelrum'
      fullPath: '/rum/enkelrum'
      preLoaderRoute: typeof RumEnkelrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rum/dubbelrum': {
      id: '/rum/dubbelrum'
      path: '/rum/dubbelrum'
      fullPath: '/rum/dubbelrum'
      preLoaderRoute: typeof RumDubbelrumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BokaKonferensRoute: BokaKonferensRoute,
  BokaRumRoute: BokaRumRoute,
  GalleriRoute: GalleriRoute,
  KontaktRoute: KontaktRoute,
  LangtidsboendeRoute: LangtidsboendeRoute,
  NyheterRoute: NyheterRoute,
  RumDubbelrumRoute: RumDubbelrumRoute,
  RumEnkelrumRoute: RumEnkelrumRoute,
  RumGrandLitRoute: RumGrandLitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
